name: New Students API Pipeline

on:
  push:
    branches:
      - main

env:
  NODE_ENV: ${{secrets.NODE_ENV}}
  PORT: ${{secrets.PORT}}

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run build
        run: npm run build
      - name: List directory
        run: ls dist
